# Generated by Django 5.2.4 on 2025-07-09 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=255)),
                ("time", models.TimeField()),
                ("action", models.CharField(max_length=255)),
                ("is_pleasant", models.BooleanField(default=False)),
                ("reward", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "duration",
                    models.PositiveIntegerField(help_text="Duration in seconds"),
                ),
                ("frequency", models.PositiveIntegerField(default=1)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "linked_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                    ),
                ),
            ],
        ),
    ]
